import { Product } from './product.model';

export const PRODUCTS_MOCK: Product[] = [
  {
    id: 1,
    nombre: 'Taza recta polímero',
    descripcionCorta: 'Totalmente personalizable, consultar por cantidad.',
    infoModal: 'Totalmente personalizable, consultar por cantidad.',
    img: 'https://http2.mlstatic.com/D_NQ_NP_815250-MLA49035064606_022022-O.webp',
    imagenes: [
      'https://http2.mlstatic.com/D_NQ_NP_815250-MLA49035064606_022022-O.webp',
      'https://http2.mlstatic.com/D_NQ_NP_815250-MLA49035064606_022022-O.webp',
      './assets/productos/taza-polimero-3.png',
    ],
    colores: ['ladrillo', 'azul', 'celeste'],
    servicios: ['SUBLIMABLE'],
    variantes: [
      { key: '300ml', label: '300ml' },
      { key: '500ml', label: '500ml' },
    ],
    categorias: ['Tazas'],
    keywords: ['taza', 'polimero', 'sublimacion', 'merch', 'regalo'],
  },
  {
    id: 2,
    nombre: 'Taza recta cerámica',
    descripcionCorta: 'Sublimable. Ideal para regalos y empresas.',
    img: 'https://http2.mlstatic.com/D_NQ_NP_877045-MLA45450820330_042021-O.webp',
    imagenes: ['https://http2.mlstatic.com/D_NQ_NP_877045-MLA45450820330_042021-O.webp'],
    colores: ['ladrillo', 'azul', 'celeste'],
    servicios: ['SUBLIMABLE'],
    variantes: [{ key: '300ml', label: '300ml' }],
    categorias: ['Tazas'],
    keywords: ['taza', 'ceramica', 'sublimacion'],
  },
  {
    id: 3,
    nombre: 'Remera de spun blanco/gris',
    descripcionCorta: 'Bebé/niños/adultos. Spun blanco o gris.',
    img: 'https://d3ugyf2ht6aenh.cloudfront.net/stores/533/589/products/diseno-sin-titulo81-daa6f09e172fe494c015751299340641-640-0.webp',
    imagenes: [
      'https://d3ugyf2ht6aenh.cloudfront.net/stores/533/589/products/diseno-sin-titulo81-daa6f09e172fe494c015751299340641-640-0.webp',
      'assets/productos/remera-spun-2.png',
      'assets/productos/remera-spun-3.png',
    ],
    colores: ['ladrillo', 'azul', 'celeste'],
    servicios: ['DTF', 'SERIGRAFIA'],
    variantes: [
      { key: 'adultos', label: 'Adultos' },
      { key: 'ninos', label: 'Niños' },
    ],
    categorias: ['Remeras'],
    keywords: ['remera', 'spun', 'dtf', 'serigrafia', 'ropa'],
  },
  {
    id: 4,
    nombre: 'Gorra trucker niño/adultos',
    descripcionCorta: 'Personalizable. Varias combinaciones.',
    img: 'https://puraimagendigital.com.ar/2446-large_default/gorra-trucker-adulto-roja-frente-blanco.jpg',
    imagenes: ['https://puraimagendigital.com.ar/2446-large_default/gorra-trucker-adulto-roja-frente-blanco.jpg'],
    colores: ['ladrillo', 'azul', 'celeste'],
    servicios: ['VINILO', 'DTF'],
    variantes: [
      { key: 'adultos', label: 'Adultos' },
      { key: 'ninos', label: 'Niños' },
    ],
    categorias: ['Gorras'],
    keywords: ['gorra', 'trucker', 'vinilo', 'dtf'],
  },
  {
    id: 5,
    nombre: 'Llavero acrílico',
    descripcionCorta: 'Ideal souvenir. Diferentes formas.',
    img: 'https://malve.com.ar/wp-content/uploads/2019/06/pins.png',
    imagenes: ['https://malve.com.ar/wp-content/uploads/2019/06/pins.png'],
    colores: ['ladrillo', 'azul', 'celeste'],
    servicios: ['SUBLIMABLE'],
    variantes: [
      { key: 'rect', label: 'Rectangular' },
      { key: 'red', label: 'Redondo' },
    ],
    categorias: ['Llaveros'],
    keywords: ['llavero', 'acrilico', 'souvenir', 'sublimacion'],
  },
];
