export type LocalidadOption = {
  value: string;
  label: string;
};

export const PROVINCIAS_ARGENTINA: string[] = [
  'Buenos Aires',
  'CABA',
  'Catamarca',
  'Chaco',
  'Chubut',
  'Córdoba',
  'Corrientes',
  'Entre Ríos',
  'Formosa',
  'Jujuy',
  'La Pampa',
  'La Rioja',
  'Mendoza',
  'Misiones',
  'Neuquén',
  'Río Negro',
  'Salta',
  'San Juan',
  'San Luis',
  'Santa Cruz',
  'Santa Fe',
  'Santiago del Estero',
  'Tierra del Fuego',
  'Tucumán',
];

function withOtra(items: string[]): LocalidadOption[] {
  const base = items.map((x) => ({ value: x, label: x }));
  return [...base, { value: 'Otra', label: 'Otra' }];
}

export const LOCALIDADES_POR_PROVINCIA: Record<string, LocalidadOption[]> = {
  'Buenos Aires': withOtra([
    'Adrogué',
    'Avellaneda',
    'Bahía Blanca',
    'Banfield',
    'Bella Vista',
    'Benavídez',
    'Berazategui',
    'Berisso',
    'Burzaco',
    'Campana',
    'Cañuelas',
    'Capilla del Señor',
    'Carapachay',
    'Carlos Casares',
    'Carlos Tejedor',
    'Caseros',
    'Castelar',
    'Chacabuco',
    'Chascomús',
    'Chivilcoy',
    'Ciudad Evita',
    'Del Viso',
    'Dock Sud',
    'Don Torcuato',
    'El Jagüel',
    'Escobar',
    'Ezeiza',
    'Ezpeleta',
    'Florencio Varela',
    'Florida',
    'General Alvear',
    'General Belgrano',
    'General Las Heras',
    'General Madariaga',
    'General Pacheco',
    'General Pinto',
    'General Rodríguez',
    'Glew',
    'Gobernador Udaondo',
    'Grand Bourg',
    'Haedo',
    'Hudson',
    'Hurlingham',
    'Ingeniero Maschwitz',
    'Ingeniero Pablo Nogués',
    'Ituzaingó',
    'José C. Paz',
    'José Ingenieros',
    'José León Suárez',
    'Junín',
    'La Lucila',
    'La Plata',
    'La Reja',
    'Lanús',
    'Llavallol',
    'Lobos',
    'Lomas de Zamora',
    'Luján',
    'Magdalena',
    'Malvinas Argentinas',
    'Manuel Alberti',
    'Mar del Plata',
    'Mar de Ajó',
    'Marcos Paz',
    'Martínez',
    'Mercedes',
    'Merlo',
    'Miramar',
    'Monte Grande',
    'Moreno',
    'Morón',
    'Muñiz',
    'Necochea',
    'Olavarría',
    'Pablo Podestá',
    'Paso del Rey',
    'Pergamino',
    'Pilar',
    'Pinamar',
    'Plátanos',
    'Pontevedra',
    'Punta Alta',
    'Quilmes',
    'Rafael Calzada',
    'Ramos Mejía',
    'Ranelagh',
    'Remedios de Escalada',
    'Saavedra',
    'San Andrés',
    'San Antonio de Areco',
    'San Antonio de Padua',
    'San Bernardo',
    'San Fernando',
    'San Francisco Solano',
    'San Isidro',
    'San Justo',
    'San Martín',
    'San Miguel',
    'San Miguel del Monte',
    'San Nicolás',
    'Santos Lugares',
    'Sarandí',
    'Tandil',
    'Tapiales',
    'Temperley',
    'Tigre',
    'Tortuguitas',
    'Trenque Lauquen',
    'Tres Arroyos',
    'Tres de Febrero',
    'Vicente López',
    'Victoria',
    'Villa Adelina',
    'Villa Ballester',
    'Villa Bosch',
    'Villa Celina',
    'Villa Fiorito',
    'Villa Gesell',
    'Villa Luzuriaga',
    'Villa Martelli',
    'Villa Tesei',
    'Virreyes',
    'Wilde',
    'Zárate',
  ]),

  'CABA': withOtra([
    'Agronomía',
    'Almagro',
    'Balvanera',
    'Barracas',
    'Belgrano',
    'Boedo',
    'Caballito',
    'Chacarita',
    'Coghlan',
    'Colegiales',
    'Constitución',
    'Flores',
    'Floresta',
    'La Boca',
    'Liniers',
    'Mataderos',
    'Monserrat',
    'Monte Castro',
    'Nueva Pompeya',
    'Nuñez',
    'Palermo',
    'Parque Avellaneda',
    'Parque Chacabuco',
    'Parque Patricios',
    'Puerto Madero',
    'Recoleta',
    'Retiro',
    'Saavedra',
    'San Cristóbal',
    'San Nicolás',
    'San Telmo',
    'Vélez Sarsfield',
    'Versalles',
    'Villa Crespo',
    'Villa del Parque',
    'Villa Devoto',
    'Villa Lugano',
    'Villa Luro',
    'Villa Ortúzar',
    'Villa Pueyrredón',
    'Villa Real',
    'Villa Santa Rita',
    'Villa Soldati',
    'Villa Urquiza',
  ]),

  'Catamarca': withOtra([
    'Andalgalá',
    'Belén',
    'Capayán',
    'Chumbicha',
    'Fiambalá',
    'Fray Mamerto Esquiú',
    'Pomán',
    'Recreo',
    'San Fernando del Valle de Catamarca',
    'Santa María',
    'Tinogasta',
    'Valle Viejo',
  ]),

  'Chaco': withOtra([
    'Barranqueras',
    'Castelli',
    'Charata',
    'Fontana',
    'General José de San Martín',
    'Juan José Castelli',
    'Las Breñas',
    'Machagai',
    'Presidencia de la Plaza',
    'Presidencia Roque Sáenz Peña',
    'Puerto Tirol',
    'Quitilipi',
    'Resistencia',
    'Villa Ángela',
  ]),

  'Chubut': withOtra([
    'Comodoro Rivadavia',
    'Dolavon',
    'Esquel',
    'Gaiman',
    'Lago Puelo',
    'Puerto Madryn',
    'Rawson',
    'Rada Tilly',
    'Sarmiento',
    'Trelew',
  ]),

  'Córdoba': withOtra([
    'Alta Gracia',
    'Arroyito',
    'Bell Ville',
    'Capilla del Monte',
    'Colonia Caroya',
    'Cosquín',
    'Córdoba Capital',
    'Cruz del Eje',
    'Dean Funes',
    'Jesús María',
    'Laboulaye',
    'La Calera',
    'La Falda',
    'Las Varillas',
    'Leones',
    'Malagueño',
    'Marcos Juárez',
    'Mina Clavero',
    'Morteros',
    'Oncativo',
    'Río Ceballos',
    'Río Cuarto',
    'Río Segundo',
    'Río Tercero',
    'Saldán',
    'San Francisco',
    'Unquillo',
    'Villa Allende',
    'Villa Carlos Paz',
    'Villa Dolores',
    'Villa General Belgrano',
    'Villa María',
    'Villa Nueva',
  ]),

  'Corrientes': withOtra([
    'Bella Vista',
    'Corrientes Capital',
    'Curuzú Cuatiá',
    'Empedrado',
    'Esquina',
    'Goya',
    'Itatí',
    'Ituzaingó',
    'Mercedes',
    'Monte Caseros',
    'Paso de los Libres',
    'Santo Tomé',
    'Saladas',
  ]),

  'Entre Ríos': withOtra([
    'Basavilbaso',
    'Chajarí',
    'Colón',
    'Concepción del Uruguay',
    'Concordia',
    'Crespo',
    'Diamante',
    'Federación',
    'Gualeguay',
    'Gualeguaychú',
    'La Paz',
    'Nogoyá',
    'Paraná',
    'San José',
    'Victoria',
    'Villaguay',
  ]),

  'Formosa': withOtra([
    'Clorinda',
    'El Colorado',
    'Formosa Capital',
    'Ibarreta',
    'Ingeniero Juárez',
    'Laguna Blanca',
    'Pirané',
    'Pozo del Tigre',
  ]),

  'Jujuy': withOtra([
    'Abra Pampa',
    'Humahuaca',
    'La Quiaca',
    'Libertador General San Martín',
    'Monterrico',
    'Palpalá',
    'Perico',
    'San Pedro de Jujuy',
    'San Salvador de Jujuy',
    'Tilcara',
  ]),

  'La Pampa': withOtra([
    '25 de Mayo',
    'Eduardo Castex',
    'General Acha',
    'General Pico',
    'Intendente Alvear',
    'Realicó',
    'Santa Rosa',
    'Toay',
    'Victorica',
  ]),

  'La Rioja': withOtra([
    'Aimogasta',
    'Chamical',
    'Chepes',
    'Chilecito',
    'Famatina',
    'La Rioja Capital',
    'Olta',
    'Villa Unión',
  ]),

  'Mendoza': withOtra([
    'General Alvear',
    'Godoy Cruz',
    'Guaymallén',
    'Junín',
    'La Consulta',
    'Las Heras',
    'Lavalle',
    'Luján de Cuyo',
    'Maipú',
    'Malargüe',
    'Mendoza Capital',
    'Palmira',
    'Rivadavia',
    'San Carlos',
    'San Martín',
    'San Rafael',
    'Tunuyán',
    'Tupungato',
  ]),

  'Misiones': withOtra([
    'Apóstoles',
    'Aristóbulo del Valle',
    'Eldorado',
    'Leandro N. Alem',
    'Montecarlo',
    'Oberá',
    'Posadas',
    'Puerto Esperanza',
    'Puerto Iguazú',
    'San Ignacio',
  ]),

  'Neuquén': withOtra([
    'Añelo',
    'Centenario',
    'Chos Malal',
    'Cutral Có',
    'Junín de los Andes',
    'Neuquén Capital',
    'Plaza Huincul',
    'Plottier',
    'San Martín de los Andes',
    'Villa La Angostura',
    'Zapala',
  ]),

  'Río Negro': withOtra([
    'Allen',
    'Bariloche',
    'Catriel',
    'Cervantes',
    'Choele Choel',
    'Cipolletti',
    'El Bolsón',
    'General Conesa',
    'General Roca',
    'Ingeniero Jacobacci',
    'Luis Beltrán',
    'Río Colorado',
    'San Antonio Oeste',
    'Sierra Grande',
    'Viedma',
    'Villa Regina',
  ]),

  'Salta': withOtra([
    'Cafayate',
    'Cerrillos',
    'Embarcación',
    'General Güemes',
    'Joaquín V. González',
    'Metán',
    'Orán',
    'Rosario de Lerma',
    'Salta Capital',
    'San Lorenzo',
    'Tartagal',
  ]),

  'San Juan': withOtra([
    'Albardón',
    'Caucete',
    'Chimbas',
    'Pocito',
    'Rawson',
    'Rivadavia',
    'San Juan Capital',
    'Santa Lucía',
  ]),

  'San Luis': withOtra([
    'Concarán',
    'Juana Koslay',
    'La Punta',
    'Merlo',
    'San Luis Capital',
    'Tilisarao',
    'Villa Mercedes',
  ]),

  'Santa Cruz': withOtra([
    'Caleta Olivia',
    'El Calafate',
    'El Chaltén',
    'Las Heras',
    'Perito Moreno',
    'Pico Truncado',
    'Puerto Deseado',
    'Puerto San Julián',
    'Río Gallegos',
    'Río Turbio',
  ]),

  'Santa Fe': withOtra([
    'Arroyo Seco',
    'Avellaneda',
    'Cañada de Gómez',
    'Capitán Bermúdez',
    'Casilda',
    'Esperanza',
    'Firmat',
    'Funes',
    'Gálvez',
    'Granadero Baigorria',
    'Reconquista',
    'Rafaela',
    'Rosario',
    'Roldán',
    'San Cristóbal',
    'San Javier',
    'San Jorge',
    'San Justo',
    'San Lorenzo',
    'Santa Fe Capital',
    'Santo Tomé',
    'Sunchales',
    'Venado Tuerto',
    'Villa Constitución',
    'Villa Gobernador Gálvez',
  ]),

  'Santiago del Estero': withOtra([
    'Añatuya',
    'Bandera',
    'Fernández',
    'Frías',
    'La Banda',
    'Las Termas de Río Hondo',
    'Loreto',
    'Monte Quemado',
    'Quimilí',
    'Santiago del Estero Capital',
  ]),

  'Tierra del Fuego': withOtra([
    'Río Grande',
    'Tolhuin',
    'Ushuaia',
  ]),

  'Tucumán': withOtra([
    'Aguilares',
    'Banda del Río Salí',
    'Concepción',
    'Famaillá',
    'Juan Bautista Alberdi',
    'Lules',
    'Monteros',
    'San Isidro de Lules',
    'San Miguel de Tucumán',
    'Tafí del Valle',
    'Tafí Viejo',
    'Yerba Buena',
  ]),
};

export function getLocalidadesByProvincia(provincia: string): LocalidadOption[] {
  return LOCALIDADES_POR_PROVINCIA[provincia] ?? [{ value: 'Otra', label: 'Otra' }];
}